version: '3.8'

services:
  # Base de datos para productos
  mysql-products:
    image: mysql
    container_name: mysql-products
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - lucho-express-network
    restart: always

  # Base de datos para auth
  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    networks:
      - lucho-express-network
    restart: always

  # Base de datos para clientes
  postgres-customers:
    image: postgres:latest
    container_name: postgres-customers
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customers_db
    ports:
      - "5432:5432"
    networks:
      - lucho-express-network
    restart: always

  # Base de datos para pedidos
  order-mysql:
    image: mysql
    container_name: order-mysql
    environment:
      MYSQL_DATABASE: orders_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - lucho-express-network
    restart: always

  # Redis para el microservicio de tracking (Base de datos en memoria)
  redis-tracking-service:
    image: redis:7-alpine
    container_name: redis-tracking-service
    ports:
      - "6379:6379"
    networks:
      - lucho-express-network
    restart: always

  # RabbitMQ para mensajería
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lucho-express-network
    restart: always

  # Base de datos para ms-chat
  postgres-chat:
    image: postgres:latest
    container_name: postgres-chat
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat_db
    ports:
      - "5434:5432"
    networks:
      - lucho-express-network
    restart: always

networks:
  lucho-express-network:
    name: lucho-express-network
    driver: bridge