spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: 
              - "http://localhost:4200"
              - "http://127.0.0.1:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: ms-auth
          uri: http://ms-auth-lucho-express:8081
          predicates:
            - Path=/auth/**
        - id: ms-customer
          uri: http://ms-customer-lucho-express:8082
          predicates:
            - Path=/api/customers/**
        - id: ms-order
          uri: http://ms-orders-lucho-express:8084
          predicates:
            - Path=/api/orders/**
        - id: ms-products
          uri: http://ms-product-lucho-express:8085
          predicates:
            - Path=/api/products/**
        - id: ms-product-categories
          uri: http://ms-product-lucho-express:8085
          predicates:
            - Path=/api/categories-with-products/**
        - id: ms-categories
          uri: http://ms-product-lucho-express:8085
          predicates:
            - Path=/api/categories/**
        - id: ms-tracking-orders
          uri: http://ms-tracking-lucho-express:8086
          predicates:
            - Path=/api/tracking/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
